### ISSUE TITLE
README images

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#1]
![sgload](https://cloud.githubusercontent.com/assets/296876/18367549/8d995bf4-75d0-11e6-8d91-a0056b00346e.png)

**Comment by mschoch** [comment]
is this some weird hack i don't know to put images inside the README without putting them in the repo?

**Comment by tleyden** [comment]
@mschoch yep!  See http://solutionoptimist.com/2013/12/28/awesome-github-tricks/
