### ISSUE TITLE
Long running test (8 hours)

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#28]
Tests in progress:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/124/

**Comment by tleyden** [comment]
It seems to be working much better when kicked off via the CLI rather than via Jenkins:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/153/consoleFull

^^ this jenkins run stopped with logs:

```
14:53:31 execute_sgload done.
```

even though none of the updaters or readers finished.  It might be hitting a timeout when running a remote command.

Possible quickfix workaround: launch it in `screen` rather than synchronous paramiko ssh command

**Comment by tleyden** [comment]
Blocked by https://github.com/couchbaselabs/sgload/issues/32

**Comment by tleyden** [comment]
In [jenkins run 196](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/196/) the test ran successfully and took 3 hours.

In [jenkins run 197](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/197/) the test ran for 7 hours, but we killed it because throughput was fairly low (500 ops/sec on couchbase server bucket) and were seeing logs like:

```
_time=2016-12-20T10:17:05.312-08:00 _level=INFO _msg=go-couchbase: call to Do("835-writer-user-14-dc9b6d15-0c62-4fd3-bf5c-b095149012f5") in github.com/couchbase/go-couchbase.(*Bucket).casNext took 3.07313
```

Retry with:

- Set docs revs limit so docs don't grow out of control
- Use less docs so that bucket limits aren't being hit

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/198/

Other things to try:

- Shut down sg accels to reduce load on couchbase server
- Run with larger sized Couchbase Server instances on AWS or re-size the VM's

**Comment by tleyden** [comment]
@adamcfraser in [perf run 198](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/198/console) with lower revs limit and less docs, the updaters are putting a consistent load on the data-bucket of about 3.75K ops/sec, and I'm not seeing any go-couchbase timing warnings in the logs:

<img width="1239" alt="screen shot 2016-12-20 at 10 49 24 am" src="https://cloud.githubusercontent.com/assets/296876/21363596/229b19aa-c6a2-11e6-9437-aa1ace390c4f.png">

**Comment by tleyden** [comment]
<img width="1105" alt="screen shot 2016-12-20 at 10 51 07 am" src="https://cloud.githubusercontent.com/assets/296876/21363618/3e18f2e2-c6a2-11e6-87e3-0a8f3fc4acd1.png">

**Comment by tleyden** [comment]
However, it does look like the data bucket is filling up fairly quickly

<img width="1113" alt="screen shot 2016-12-20 at 10 52 11 am" src="https://cloud.githubusercontent.com/assets/296876/21363658/6ddfadcc-c6a2-11e6-9b9b-d3fdc935f6b2.png">

**Comment by tleyden** [comment]
Actually, it looks like it's not monotonically increasing, probably as TTL revision docs expire

<img width="1132" alt="screen shot 2016-12-20 at 10 54 05 am" src="https://cloud.githubusercontent.com/assets/296876/21363753/be085a2e-c6a2-11e6-9783-b476d550ab52.png">

**Comment by tleyden** [comment]
Running [perf test 199](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/199/), and the ops just dropped off:

<img width="1084" alt="screen shot 2016-12-20 at 1 13 43 pm" src="https://cloud.githubusercontent.com/assets/296876/21368180/42cbb3b0-c6b6-11e6-8e82-f9a400bb8549.png">

**Comment by tleyden** [comment]
Also in [perf test 199](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/199/), I noticed the ops/sec on the index bucket drop to 0:

![screen shot 2016-12-20 at 1 31 11 pm](https://cloud.githubusercontent.com/assets/296876/21368739/afd33d5a-c6b8-11e6-8002-fe21c5394714.png)

In the logs:

```
2016-12-20T13:28:56.735-08:00 WARNING: RetryLoop for WriteCas with key _idx_c:_idx_stableSeq:clock-60 giving up after 11 attempts -- base.RetryLoop() at util.go:336
2016-12-20T13:28:56.736-08:00 WARNING: RetryLoop for WriteCas with key _idx_c:_idx_stableSeq:clock-63 giving up after 11 attempts -- base.RetryLoop() at util.go:336
2016-12-20T13:28:56.736-08:00 WARNING: RetryLoop for WriteCas with key _idx_c:_idx_stableSeq:clock-47 giving up after 11 attempts -- base.RetryLoop() at util.go:336
2016-12-20T13:28:56.736-08:00 WARNING: RetryLoop for WriteCas with key _idx_c:_idx_stableSeq:clock-18 giving up after 11 attempts -- base.RetryLoop() at util.go:336
2016-12-20T13:28:56.737-08:00 WARNING: RetryLoop for WriteCas with key _idx_c:_idx_stableSeq:clock-30 giving up after 11 attempts -- base.RetryLoop() at util.go:336
2016-12-20 13:29:19.441599 I | Error sending heartbeat: MCResponse status=TMPFAIL, opcode=SET, opaque=0, msg: Temporary failure
_time=2016-12-20T13:29:28.264-08:00 _level=INFO _msg=go-couchbase: call to ViewCustom("cbgt", "heartbeats") in github.com/couchbase/cb-heartbeat.couchbaseHeartBeater.viewQueryHeartbeatDocs to
ok 8.79088586s
2016/12/20 13:29:45 janitor: awakes, op: kick, msg: cfg changed, key: planPIndexes
2016/12/20 13:29:45 planner: awakes, op: kick, msg: cfg changed, key: nodeDefs-wanted
2016/12/20 13:29:45 planner: once, reason: cfg changed, key: nodeDefs-wanted
2016/12/20 13:29:45 janitor: pindexes to remove: 0
2016/12/20 13:29:45 janitor: pindexes to add: 0
2016/12/20 13:29:45 janitor: feeds to remove: 0
2016/12/20 13:29:45 janitor: feeds to add: 0
```

Note the view query to the heartbeat view took 8s: `ViewCustom("cbgt", "heartbeats") in github.com/couchbase/cb-heartbeat.couchbaseHeartBeater.viewQueryHeartbeatDocs to
ok 8.79088586s`

**Comment by tleyden** [comment]
I started a cluster on AWS with much higher RAM (75 GB!) and kicked off a test on the command line using the same params as [test run 199](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/199/parameters/), which is doing 10K docs and 5K updates per doc (no readers)

![screen shot 2016-12-20 at 5 27 33 pm](https://cloud.githubusercontent.com/assets/296876/21374203/e0dc2012-c6d9-11e6-84da-88681e1cca1e.png)

![screen shot 2016-12-20 at 5 27 41 pm](https://cloud.githubusercontent.com/assets/296876/21374207/e3a39492-c6d9-11e6-8d2f-645dc9f3fd0f.png)

The ops have been steady at 2K ops/sec on the data bucket.  The ops are lower than I expected, which appears to be due to the Sync Gateway being fairly limited on the CPU (2 CPUs) and fully maxed out at 199%:

![screen shot 2016-12-20 at 5 30 45 pm](https://cloud.githubusercontent.com/assets/296876/21374226/1025ba04-c6da-11e6-931a-267f50a30f8b.png)

It's been running for an hour and the updaters are about ~10% done.

**Comment by tleyden** [comment]
I spun up a larger AWS cluster where all machines are [m4.4xlarge](https://aws.amazon.com/ec2/instance-types/), and while running sgload with the same parameters as https://github.com/couchbaselabs/sgload/issues/28#issuecomment-268409488, now I'm seeing sustained **12K** ops/sec

![screen shot 2016-12-20 at 6 32 45 pm](https://cloud.githubusercontent.com/assets/296876/21375517/e50663b0-c6e2-11e6-9d01-e9bb189352be.png)

**Comment by tleyden** [comment]
Sync Gateway resource usage


![screen shot 2016-12-20 at 6 36 33 pm](https://cloud.githubusercontent.com/assets/296876/21375581/675a64f6-c6e3-11e6-89fb-8631d1df65f7.png)


SG accel resource usage

![screen shot 2016-12-20 at 6 37 23 pm](https://cloud.githubusercontent.com/assets/296876/21375588/70668282-c6e3-11e6-96fd-571c1488b0c7.png)

SG Load resource usage

![screen shot 2016-12-20 at 6 35 52 pm](https://cloud.githubusercontent.com/assets/296876/21375601/7ffd9f28-c6e3-11e6-87bb-d20280bdb637.png)

**Comment by tleyden** [comment]
`sg_accel` has a lot of unused resource capacity since it's not even maxing out 2 cores, and there are 16 cores total in the machine.  Even more true for `sgload`

**Comment by tleyden** [comment]
<img width="1144" alt="screen shot 2016-12-20 at 8 20 26 pm" src="https://cloud.githubusercontent.com/assets/296876/21377244/c50a402c-c6f1-11e6-86b2-8c7279e07cd5.png">

The updaters are about 75% done at this point

**Comment by adamcfraser** [comment]
@tleyden For a 10K docs, 5K updates scenario, how are we ending up with 3.3M docs in the bucket?  Are we finishing all 5K updates in 5-10 minutes, so there are 3M+ old revision bodies pending expiry?  

Or maybe a case of the expiry pager not running yet?

**Comment by tleyden** [comment]
Great catch!  I will look into it -- there might be a bug where the updaters are accidentally writing new docs rather than updating existing

**Comment by tleyden** [comment]
I haven't dug into the sgload code yet, but some more data points:

* The sgload test finished
* 5 mins ago when I saw your comment, I checked the couchbase server data-bucket and it had ~6M docs.
* 2 mins ago it had ~3.2 M
* The data-bucket compaction is still running

<img width="1111" alt="screen shot 2016-12-20 at 9 16 23 pm" src="https://cloud.githubusercontent.com/assets/296876/21378245/e370dcf8-c6f9-11e6-8412-a938b27fbb5f.png">

<img width="1127" alt="screen shot 2016-12-20 at 9 16 42 pm" src="https://cloud.githubusercontent.com/assets/296876/21378241/e0a507a6-c6f9-11e6-9bf2-9b6b623287ec.png">

**Comment by tleyden** [comment]
> there might be a bug where the updaters are accidentally writing new docs rather than updating existing

Doesn't look like it since the data-bucket has been compacted down to 33K docs

<img width="1142" alt="screen shot 2016-12-20 at 9 29 40 pm" src="https://cloud.githubusercontent.com/assets/296876/21378478/6fde886a-c6fb-11e6-9f51-80415078ae5d.png">

Also I did a local test of sgload on a fresh SG instance:

```
go run main.go gateload --createreaders --createwriters --numreaders 0 --numrevsperdoc 5 
--numupdaters 10 --numwriters 10 --numdocs 1000 --numchannels 10 
--sg-url http://localhost:4984/db/ --batchsize 10
```

and then queried `_all_docs` on the admin port, and it showed 10K docs:

```
$ curl http://localhost:4985/db/_all_docs | grep -i total_rows
"total_rows":1000,"update_seq":6012}
```

**Comment by adamcfraser** [comment]
That's an interesting data point - I hadn't considered the overhead associated with the temporary backups if the doc wasn't purged close to immediately upon expiry, which looks like it might be what's going on.

10K docs, 5K revisions each would end up with 50M backups being written over the lifetime of the  test, so having several million pending purge may not be surprising.

**Comment by tleyden** [comment]
One thing to also note, in https://github.com/couchbaselabs/sgload/issues/28#issuecomment-268439386 notice that there are only 2 couchbase server nodes.  It looks like one crashed since it ran out of disk space.  Part of the problem is that they only have 60GB drives attached.

**Comment by tleyden** [comment]
The first AWS test (mentioned in https://github.com/couchbaselabs/sgload/issues/28#issuecomment-268409488) has finished and ran for a total of approx ~12 hours with a sustained load.

<img width="1056" alt="screen shot 2016-12-21 at 8 24 25 am" src="https://cloud.githubusercontent.com/assets/296876/21397047/1ffb43a4-c757-11e6-88ab-b49edb149683.png">

From an sgload perspective, this looks to be complete, so I'm closing out this ticket.
