### ISSUE TITLE
Deal with transient errors

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#3]
Log 500 errors

If get a 500 error, retry and log a stat. 

New counters
- bulk_doc push error
- changes pull error
- bulk_get pull error

True for anything .. reading changes feed or pushing bulk docs

**Comment by tleyden** [comment]
In http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/47/console, getting:

```
14:01:22 t=2016-10-17T14:01:21-0700 lvl=eror msg="Error calling pullMoreDocs" agent.ID=2 since=1-13 err="Unexpected response status for POST request: 500"
14:01:22 t=2016-10-17T14:01:21-0700 lvl=info msg="Reader finished" agent.ID=2 numdocs=0
14:01:22 
14:01:22 2016/10/17 14:01:20 glNumReaders: 10
14:01:22 panic: Error calling pullMoreDoc: Unexpected response status for POST request: 500
14:01:22 
14:01:22 goroutine 21 [running]:
14:01:22 github.com/couchbaselabs/sgload/sgload.(*Reader).Run(0xc82008ac00)
14:01:22    /opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:101 +0x69f
14:01:22 created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startReaders
14:01:22    /opt/go/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:232 +0x226
```

**Comment by tleyden** [comment]
@adamcfraser post parameters to flesh out 500 errors

**Comment by adamcfraser** [comment]
I've hit 500 errors regularly when my CBS bucket runs out of memory allocation, but that won't really help you with the retry handling.

You might be able to generate 500s by just cranking up the number of writers.

**Comment by tleyden** [comment]
Another panic which may be related to this:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/103/console

```
18:49:26 
18:49:26 t=2016-11-16T18:49:26-0800 lvl=info msg="Reader finished" agent.ID=78 numdocs=1
18:49:26 
18:49:26 Exception calling execute_sgload: Detected panic: panic: Error calling pullMoreDoc: RetryLoop for pullMoreDocs giving up after 8 attempts
18:49:26 
18:49:26 Traceback (most recent call last):
18:49:26   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 74, in execute_sgload
18:49:26     stream_output(stderr, sys.stderr, abort_if_panic=True)
18:49:26   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 92, in stream_output
18:49:26     raise Exception("Detected panic: {}".format(line))
18:49:26 Exception: Detected panic: panic: Error calling pullMoreDoc: RetryLoop for pullMoreDocs giving up after 8 attempts
18:49:26 
18:49:26 
18:49:26 Traceback (most recent call last):
18:49:26   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 156, in <module>
18:49:26     sg_host_main
18:49:26   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 41, in run_sgload_on_single_loadgenerator
18:49:26     execute_sgload(lg_host, sgload_arg_list, sg_host)
18:49:26   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 84, in execute_sgload
18:49:26     raise e
18:49:26 Exception: Detected panic: panic: Error calling pullMoreDoc: RetryLoop for pullMoreDocs giving up after 8 attempts
18:49:26 
18:49:26 Build step 'Execute shell' marked build as failure
18:49:26 Archiving artifacts
18:49:26 Finished: FAILURE
```

**Comment by tleyden** [comment]
Challenges:

- How do we handle https://github.com/couchbaselabs/sgload/issues/3#issuecomment-261335198 -- just panic as we are currently?

- We are doing accounting in the reader to see if we've read all the revisions (`func (r *Reader) isFinished(latestDocIdRevs map[string]int) bool`), and so we can't easily just ignore revisions with errors .. need to keep retrying until we get them.  Complicates logic a bit, especially with `bulk_get` and partial failures.  (do we only retry the ones that failed?  or just retry entire `bulk_get`

- How many times to retry?  Backoff retry?

**Comment by tleyden** [comment]
- Add retry / backoff loop on all requests
- Retry bulk_get: just retry entire bulk_get 
- If retry loop exhausted, then panic (should rarely / never happen)
- Log stats to stats to statsd
- Update grafana panels to show these stats
